### ISSUE TITLE
gulp build errors missing module serve-static

### ISSUE THREAD

**Issue by augustf** [augustf/jira-train-dashboard#2]
gulp build
module.js:327
    throw err;
    ^

Error: Cannot find module 'serve-static'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/august/Desktop/jira-train-dashboard/gulpfile.js:11:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by augustf** [comment]
Resolved in 57cb6459a0e0c9743942a926d9243dccc88b5a8a
